name: Android debug build

on:
  push:
    branches:
      - main

jobs:
  build:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Install JS dependencies
        run: yarn install
      - uses: malinskiy/action-android/install-sdk@release/0.0.7
      - run: cd android && ./gradlew bundleDebug
