name: ios Release build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Install JS dependencies
        run: yarn install
      - name: Install iOS dependencies
        run: cd ios && pod install
      - name: Build the iOS app
        env:
          FASTLANE_SESSION: ${{secrets.FASTLANE_SESSION}}
        run: |
          fastlane sigh -a fr.tpxp.reactnative.example
          fastlane gym --workspace "ios/ExampleRNApp.xcworkspace" --scheme "ExampleRNApp" --configuration Release
