name: ios Release build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Install JS dependencies
        run: yarn install
      - name: Install iOS dependencies
        run: cd ios && pod install
      - name: Build the iOS app
        env:
          FASTLANE_SESSION: ${{secrets.FASTLANE_SESSION}}
          FASTLANE_USER: ${{secrets.FASTLANE_USER}}
          MATCH_GIT_PRIVATE_KEY: ${{secrets.MATCH_GIT_PRIVATE_KEY}}
          MATCH_PASSWORD: ${{secrets.MATCH_PASSWORD}}
          MATCH_KEYCHAIN_PASSWORD: ${{secrets.MATCH_PASSWORD}}
          MATCH_KEYCHAIN_NAME: ci_keychain
        run: |
          bundle install
          bundle exec fastlane run create_keychain password:$MATCH_KEYCHAIN_PASSWORD default_keychain:true name:$MATCH_KEYCHAIN_NAME timeout:false
          bundle exec fastlane build
